### ISSUE TITLE
Ability to add additional pages for generic documentation.

### ISSUE THREAD

**Issue by dahliacreative** [devnacho/mountain_view#24]
Hi, we are currently using mountain view on a project, and it is awesome, but one thing we'd find really useful is to add some extra pages to the style guide for things that aren't components, like for grid layouts, coding styles, generic classes etc.

It would also be good if you can add some extra documentation to you component YML, for instance just a paragraph at the top of the page where you could list out available modifier classes etc.

**Comment by jgnatch** [comment]
Hey @dahliacreative, 

It sounds like a great idea! It's something I wanted to do but couldn't find the time.

Feel free to open a PR or I'll try doing it during these weeks.

Cheers!

**Comment by GustavoCaso** [comment]
@jgnatch The pagination would be part of the `yml` file configuration or more like a global configuration ?
The extra documentation would be something I will take the time because seems simple, but for extra pages I would like to have more information.

Thanks.

**Comment by GustavoCaso** [comment]
@jgnatch @kitop guys what you think about adding some configuration for adding extra pages to the styleguide like 
```ruby
MountainView.configure do |config|
  config.included_extra_pages = ['grid', 'code_style']
end
```
Each element in the array will create a different page with own style and javascript files.
What you think ?

**Comment by kitop** [comment]
@GustavoCaso something like that may work. Where would those pages live?

**Comment by GustavoCaso** [comment]
Hi @kitop.

Doing a recap on this issue, I think that there could be multiple options for where the pages could live:
* Inside the gem, like the `show` of the styleguide (but I think it would not give a lot of flexibility for the user)
* Inside the user application, maybe a different structure but similar to the `components`, given the user flexibility to decide how they want to display the information
* The last one I thought could be in the `tmp` folder or create some kind of `engine` (but being honest non of does really like me)

What do you think ? @kitop

**Comment by kitop** [comment]
@GustavoCaso I like option 2!
The user may be able to extend the styleguide controller and add views to it, and it'd be a matter of just adding the routes to the engine—which could be done with a config setting or similar.
As far as I remember, there's kind of template inheritance with Engines.

Thoughts?

**Comment by GustavoCaso** [comment]
@kitop I like the idea of using some kind of configuration like the one above, this will create the template, the routes and even the links inside the styleguide, but the user will have all control for adding, removing and editing the page, at his/her will.

**Comment by kitop** [comment]
@GustavoCaso That could definitively work!
So, the user will just declare custom pages in the config, and then add the views in `app/views/mountain_view/styleguide/<page>`, or something like that, right?

@jgnatch thoughts?

**Comment by GustavoCaso** [comment]
@kitop Yes that is what I had in mind, also automate the route creation or even adding the links in the sidebar of the styleguide.

What do you think ?

**Comment by kitop** [comment]
@GustavoCaso Yes, that'd be automatically added from the configuration setting :)

**Comment by GustavoCaso** [comment]
Great @kitop.

Now that we are in the same page I will start developing.

I hope to have a PR as soon as possible

**Comment by kitop** [comment]
Awesome!!! Thank you so much! :)

@dahliacreative your input is very welcomed as well!

**Comment by jgnatch** [comment]
@kitop @GustavoCaso totally agree with this solution. Option 2 is the one I like most too!

**Comment by GustavoCaso** [comment]
@kitop we can close this one 

Also any feature plans for next release ?

**Comment by kitop** [comment]
Closed!
No specific plans yet, but ideas and feedback are more than welcome!
