### ISSUE TITLE
Trying and failing to have my components use vendor mixins (bootstrap, bourbon)

### ISSUE THREAD

**Issue by dskoziol** [devnacho/mountain_view#30]
Hey, I'm a bit new to this, so maybe there's a simple fix to my problem. I'm trying to see if I can incorporate Mountain View into a project I'm doing, so I'm building a single component first and seeing how it goes. The problem is that our project is using bootstrap and bourbon (through the bootstrap-sass and bourbon gems), and I'm not finding an easy way to make them work with the Mountain View component I'm making. 

I thought I'd be able to do the Global Stylesheet initializer in the guide, and put `config.included_stylesheets = ["bootstrap-custom", "bourbon"]`. That doesn't seem to do anything. I'm not even sure how to to debug the initializer. If I do `config.included_stylesheets=["boooooooooooootstrap"]` it doesn't throw any type of error on my server or development log. So I don't know if it's even doing anything with the bootstrap file when I use the actual name.

I then tried changing `*= require mountain_view` to `@import "mountain_view";` and putting it after my Bootstrap import in application.scss, but that's giving me the same errors from my component SCSS (`Undefined mixin 'make-xs-column'.`), so it's not seeing the bootstrap Bootstrap stuff.

I then tried adding `config.assets.paths << Rails.root.join("components")` to config/application.rb and just manually importing the individual component in the correct spot in application.scss. That works! However, (1) it'd mean I'd have to manually import the CSS of every component, and (2) it doesn't work in the autogenerated Style Guide. I get the same `Undefined mixin` error.

Am I maybe doing the global stylesheet inclusion incorrectly? Or there's a special way to do it when your working with stylesheets that are generated by gems? I don't have a lot of Rails expertise, so it might be something as simple as being too specific or general with my pathnames.

**Comment by dskoziol** [comment]
Would it be possible to `@import mountain_view` where I want it to go in my asset pipeline in application.scss (after bootstrap, variables, and anything else that I want to use in the component assets), and direct the style guide to use this file for CSS? It seems like `//= require` statements are following out of favor anyway (from RailsGuides: `If you want to use multiple Sass files, you should generally use the Sass @import rule
instead of these Sprockets directives. When using Sprockets directives, Sass files exist within
their own scope, making variables or mixins only available within the document they were defined in.`)

Or maybe there's some way I can get this to work without changing anything in the gem.

**Comment by alexandra-aas** [comment]
I'd like to upvote this.

**Comment by kitop** [comment]
For bourbon, you should be able do do `@import "bourbon"` in the components that use it. As it's all mixins, it should generate duplicate CSS.

For bootstrap, using `config.included_stylesheets = ["bootstrap"]` should do it, be aware you should restart your development server after changing the initializer.

Let me know if any of this helps. If not, an example repo withe just the things that are not working would be really helpful for debugging.
