### ISSUE TITLE
component class gives undefined local variable or method 

### ISSUE THREAD

**Issue by gazaston** [devnacho/mountain_view#41]
If I add a class e.g. header_component.rb to my component, do I need to do anything else? I'm getting undefined local variable or method errors, seems the class is not being loaded?

**Comment by drakmail** [comment]
Does you defined a properties in header_component.rb?

**Comment by gazaston** [comment]
Yeah, code here:

components/header/header.html.haml
```
class HeaderComponent
  properties :title

  def title
    properties[:title].titleize
  end

end
```

components/header/header_component.rb
```
.header
  %h1
    This is a header component with the title: #{title}
```

**Comment by drakmail** [comment]
It should be:

```ruby
class HeaderComponent
  property :title

  def title
    properties[:title].titleize
  end

end
```

**Comment by drakmail** [comment]
Oh, I'm forgot one important moment:

1. You really can use `properties`
2. Maybe you must use a gem from github, because current version on rubygems doesn't include a Presenter class. Just change declaration in you Gemfile to: `gem 'mountain_view', github: "devnacho/mountain_view"`

**Comment by tombeynon** [comment]
You also need your HeaderComponent to inherit from MountainView::Presenter

**Comment by gazaston** [comment]
Getting the gem from github fixed it. 

Tom, thanks for the sanity check — my code has the inheritance, but I forgot to include it in my example :)

**Comment by kitop** [comment]
A new version with these changes is going to be released very soon!
Thanks all for your help and interest.
