### ISSUE TITLE
Gem version out of date with docs

### ISSUE THREAD

**Issue by jweissman** [devnacho/mountain_view#42]
Just ran into this -- the new `Presenter` class (added about a month ago) doesn't yet exist in the gem version (bumped about 3 months ago)

**Comment by jweissman** [comment]
This is workaround-able with something like this in your Gemfile:

    gem 'mountain_view', github: 'devnacho/mountain_view'

**Comment by kitop** [comment]
Just released version 0.9.0 with this change :)

Thanks for your patience!
