### ISSUE TITLE
Using "label" as a component property name.

### ISSUE THREAD

**Issue by jonathanrbowman** [devnacho/mountain_view#44]
Sorry if this has already been addressed somewhere, but I generated a component called `button` and declared `label` as one of its `properties`.

When trying to use it, though, rails gives me this error:
```
Showing app/components/button/_button.html.erb

wrong number of arguments (0 for 2..4)

<div class="c-button">
  <p><%= label %></p>   <!-- this line has the error -->
</div>
```

Changing it from `label` to `button_label`, or anything else, lets it work without issue. Is `label` a reserved property name in Mountain View?

**Comment by kitop** [comment]
`label` is an existing method in Rails: http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-label

I'd definitively try to use a different name for that property, or create an alias for it if you're using a component class.
``` ruby
def button_label
  properties[:label]
end
```

**Comment by jonathanrbowman** [comment]
Whoops, thanks for letting me know and for the suggestion!
