### ISSUE TITLE
Adjusting MountainView::Engine routes

### ISSUE THREAD

**Issue by MikeRogers0** [devnacho/mountain_view#45]
Is there a way to change the mountain_view mounted engine styleguide path from (When I run `rake routes`):

```
Routes for MountainView::Engine:
            root GET  /                         mountain_view/styleguide#index
styleguide_index GET  /styleguide(.:format)     mountain_view/styleguide#index
      styleguide GET  /styleguide/:id(.:format) mountain_view/styleguide#show
```

to 

```
Routes for MountainView::Engine:
            root GET  /                         mountain_view/styleguide#index
styleguide_index GET  /(.:format)     mountain_view/styleguide#index
      styleguide GET  /:id(.:format) mountain_view/styleguide#show
```

I've mounted my engine on a subdomain like:

```
  constraints subdomain: "style" do
    mount MountainView::Engine => "/"
  end
```

**Comment by tombeynon** [comment]
Hey @MikeRogers0 - fancy seeing you here 😉

Setting the styleguide resource to use `/` for it's path isn't possible with the current setup - see [config/routes](https://github.com/devnacho/mountain_view/blob/master/config/routes.rb#L4). 

It would be pretty easy to [add a config](https://github.com/devnacho/mountain_view/blob/master/lib/mountain_view/configuration.rb) for `styleguide_path` (defaulting to `'styleguide'`), and just adjust the route resource to `resources :styleguide, only: [:index, :show], path: MountainView.configuration.styleguide_path`. 

Not sure if @kitop or @devnacho would be happy with this, but it seems like a pretty useful config option to me.

**Comment by kitop** [comment]
@MikeRogers0 Thanks for reaching out. As @tombeynon said, that is not possible _right now_, but it would actually be a very useful config option.

More than happy to accept PR's if you want to work on it, otherwise I can give it a look sometime this weekend.

**Comment by devnacho** [comment]
@MikeRogers0 @tombeynon I agree with @kitop that this would be very useful 😃

**Comment by MikeRogers0** [comment]
#46 PR sent, it still has some work to do on it but I'd love to know your thoughts.
