### ISSUE TITLE
Advanced Yaml stubs?

### ISSUE THREAD

**Issue by Frexuz** [devnacho/mountain_view#54]
I'm not sure this is possible:

I'm doing a pagination component, quite simple:

`<%= render_component :pagination, collection: @some_collection %>`

```
<div class="layout horizontal center">
  <div class="flex-1">
    <%= paginate properties[:collection] %>
  </div>
  <div>
    <%= page_entries_info properties[:collection] %>.
  </div>
</div>
```

Would it be possible to create stubs for this somehow? The `paginate` method requires a `Kaminari::PaginatableArray` 

Obviously, this doesn't work

```
-
  :collection:
    - 1
    - 2
```

**Comment by kitop** [comment]
You can serialize an object in YAML by adding an specific comment, eg:

```ruby
module Foo
  class Bar
    attr_reader :a, :b
    def initialize(a, b)
      @a = a
      @b = b
    end
  end
end
```

```yaml
--- !ruby/object:Foo::Bar
a: "Hello"
b: "World"
```

For more info: http://yaml.org/YAML_for_ruby.html#objects

That may help point in the right direction?

**Comment by Frexuz** [comment]
Thanks :)
