### ISSUE TITLE
Order of the components in sidebar

### ISSUE THREAD

**Issue by Spone** [devnacho/mountain_view#60]
Hello there,

I can't figure out why my components are not displayed in alphabetical order in my styleguide sidebar. Is there a way to force this (without adding some specific logic in my layout)?

![image](https://user-images.githubusercontent.com/38524/29405339-ed03ad08-833d-11e7-954e-ec4484fc3bc8.png)

I think it should be the default, what do you think?

Thanks

**Comment by Spone** [comment]
I mean, I can have this in my layout:

    mv_components.sort_by(&:name).each do |component|

But if you think it should be the default, I'd be happy to prepare a PR for this.

**Comment by kitop** [comment]
Great point @Spone! Yeah, it should definitively be the default.

I'll push the change and release a patch version in a bit. 

Thanks for the input!!

**Comment by kitop** [comment]
Just out of curiosity, in what OS and ruby version are you noticing this?

**Comment by Spone** [comment]
Ubuntu 16.04 LTS, Ruby 2.4.1 (yeah it's pretty weird that the file system returns them in this order)

**Comment by Spone** [comment]
Also, it's a detail but I think you should consider using:

    link_to_unless_current component.title, styleguide_path(id: component.name)

instead of

    = link_to component.title, styleguide_path(id: component.name)

So the current component is shown differently.

**Comment by kitop** [comment]
@Spone that's a good point to! Will update and release in the same version bump :)

**Comment by kitop** [comment]
Changes released in v0.12.3 🎉 

Thanks for your help and input @Spone!!
