### ISSUE TITLE
Alias render_component to a shorter name

### ISSUE THREAD

**Issue by diegotoral** [devnacho/mountain_view#66]
I have issues with long lines so what you guys think of aliasing `render_component` to a shorter method name?

Rails itself offers alias for some of it's helpers.

- [escape_javascript](http://api.rubyonrails.org/classes/ActionView/Helpers/JavaScriptHelper.html#method-i-escape_javascript) is aliased as `j`
- [localize](http://api.rubyonrails.org/classes/ActionView/Helpers/TranslationHelper.html#method-i-localize) is aliased as `l`
- [translate](http://api.rubyonrails.org/classes/ActionView/Helpers/TranslationHelper.html#method-i-translate) as just `t`

Other gems also include shorter alias for helpers.

- komponent gem alias [component](https://github.com/komposable/komponent/blob/master/lib/komponent/komponent_helper.rb#L57) to just `cc`

**Comment by kitop** [comment]
Hi @diegotoral, thanks for the comment!

What would you suggest as the shorthand alias?

**Comment by diegotoral** [comment]
I'm currently using `rc` on a project.

**Comment by kitop** [comment]
Added and released in v0.13.0.
Thanks!!
