### ISSUE TITLE
Additional Style Guide Meta Data

### ISSUE THREAD

**Issue by ChristineP2** [devnacho/mountain_view#70]
I'm considering putting together a pull request that adds the following, and wanted to get feedback before I made the changes.  

I'd like to create new optional mv_title, mv_description, and mv_classes keys for the stubs.  These would allow for a custom titles to replace the current <component N> naming, description and usage information for the specific example, and classes for the parent div the sample resides within.  

I'd also like to move the sample underneath the title and usage instructions, instead of above it.  

Finally, I'd like to add the ability to include HTML code in the meta and the new description field I proposed. 

I'd also update the readme with the new functionality.  

ETA: Also considering adding a partial called _base.html so that basic style information can be present on the main page. If I do that, the "styleguide logo" would also become a link to the main page. I can also add the ability  to collapse the side menu to better see the responsive elements.

Am I missing something that already provides these capabilities, or a reason why they should not be offered?

**Comment by kitop** [comment]
Hi @ChristineP2 thanks for opening an issue for this!
These is very valuable feedback and feature requests. Below ask some questions to understand more the intention and use-cases, and proposing some alternatives that might already do this (although not properly documented, sorry 😞)

> I'd like to create new optional mv_title, mv_description, and mv_classes keys for the stubs. These would allow for a custom titles to replace the current naming, description and usage information for the specific example, and classes for the parent div the sample resides within.

I don't think this is documented, but you can change the component's title by overriding [`title` method](https://github.com/devnacho/mountain_view/blob/master/lib/mountain_view/component.rb#L9-L11), and add a [`meta` key in the example yml](https://github.com/devnacho/mountain_view/blob/master/app/views/mountain_view/styleguide/_example.html.erb#L2)

How are `mv_title` and `mv_description` different from overriding `title` and adding `meta` key in the yml? 

For `mv_classes`, I assume this is to override the styles. Why is this preferred over providing a custom layout for the styleguide? You can add your own `app/views/styleguide/show.html.erb` and Rails will pick that up before the gem-provided one.

> I'd also like to move the sample underneath the title and usage instructions, instead of above it.

This could be nice. If it's not too much work, can you provide a before/after example?

> Finally, I'd like to add the ability to include HTML code in the meta and the new description field I proposed.

That's a neat idea :) We should make it do that with the existing `meta` key.

> ETA: Also considering adding a partial called _base.html so that basic style information can be present on the main page. If I do that, the "styleguide logo" would also become a link to the main page. I can also add the ability to collapse the side menu to better see the responsive elements.

This sounds good!! Sounds like a PR or two on their own as it can be a big change, but really like the idea here!

**Comment by ChristineP2** [comment]
mv_title and mv_description would be for each stub example, rather than for the main heading.  The idea is that each example would have a name and our UX team could give detailed instructions on the use of each variation of the component.  The mv_classes would be used to modify the display area around the element.  For example, we have an inverse button that is meant to be white on a blue background.  I need to change the background in the style guide to make it visible.   

`
:meta:
  'Buttons are available in 4 types: primary, secondary, outline, and outline_inverse.
  Method can be get (will generate a link with a role of button) or post, submit, cancel, reset (will generate a button/formtastic button).
  If a form object is provided for the location, formtastic action will be used.
:stubs: 
-
  :mv_title: 'Primary Get Button'
  :mv_description:
    'This button should be the default, unless you are specifically instructed to use a different button, use this one.'
  :type: 'primary'
  :name: 'My Primary Link Button'
  :method: 'get'
  :location: 'javascript:void(0)'
-
  :mv_title: 'Outline Get Button'
  :mv_description:
    'This button will only be used according to the rules set forth by the UX team.'
  :type: 'outline'
  :name: 'My Outline Link Button'
  :method: 'get'
  :location: 'javascript:void(0)'
-
  :mv_title: 'Outline Inverse Get Button'
  :mv_description:
    'This button will only be used only on dark backgrounds.'
  :mv_classes: 'mv_item_background--dark'
  :type: 'outline_inverse'
  :name: 'My Outline Inverse Link Button'
  :method: 'get'
  :location: 'javascript:void(0)'
`
I am going to try and get these submitted today in several PRs.

**Comment by ChristineP2** [comment]
Screen capture of the style guide with a custom partial from my local copy of mountain_view_demo.  This is for pull request #71.  I'm fairly new to rails/ruby development, so please let me know if I violate best practice. 

![custom_home_page_content](https://user-images.githubusercontent.com/984648/46561494-85904980-c8bd-11e8-9c78-19efceba3196.PNG)

**Comment by ChristineP2** [comment]
Screen capture of the behaviors added by mv_title, mv_description, and mv_classes.  This is for pull request #72 

I'm waffling on whether or not the keys with mv_ should be hidden in the properties section.  I lean toward hiding them, and expecting someone to have a duplicate key if the actually want that value in properties.  I'll add that as a question to the pull request.

Still fairly new to rails/ruby, so please give me feedback so I can improve.  

![custom_title_desc_class](https://user-images.githubusercontent.com/984648/46565204-b169fa00-c8d2-11e8-912e-0297f8288a21.png)

**Comment by ChristineP2** [comment]
As far as positioning of the component relative to the title and usage information, it seemed like there are basically ~~4~~ 5 options:

I thought of this after I'd finished doing all the screen shots, but I could pull the title out above everything, instead of leaving it inside the description div, so that's the 5th option.

Here are the 4 options I took screenshots for:

## Before everything like it is now

![sample_before_description](https://user-images.githubusercontent.com/984648/46567590-f1dd6e00-c8fa-11e8-902b-7e3d6f3c67d3.PNG)

## Between Title and usage instructions

![sample_between_title_and_usage](https://user-images.githubusercontent.com/984648/46567591-f1dd6e00-c8fa-11e8-9f3b-ea8c544130b8.PNG)

## After Title and Usage Instructions

![sample_after_title_and_usage](https://user-images.githubusercontent.com/984648/46567589-f1dd6e00-c8fa-11e8-9207-4d04c48d5b1f.PNG)

## After Description

![sample_after_description](https://user-images.githubusercontent.com/984648/46567592-f2760480-c8fa-11e8-9b27-492542e0b369.PNG)

**Comment by ChristineP2** [comment]
Additionally, I have the following still on my short list:

* Determine whether the example code should use HAML or ERB, and display the example in whichever the component was written in
* Allow HTML in the meta and in the mv_description
* Toggle Sidebar

However, I thought we could talk about the 2 PRs that are there now, and I can come back to the above later.

**Comment by ChristineP2** [comment]
@kitop Do you want me to split the above into separate issues, instead of this long thread?

**Comment by kitop** [comment]
Hi @ChristineP2, thanks for asking. 
Please do open separate issues for the things mentioned above, it would be easier to talk about them in their own threads.

I've been super busy these past week and didn't have time to dedicate to Mountain View.
I'll come back to this issue and the PRs you opened (thank you!!) during the weekend or top of next week at most.

**Comment by ChristineP2** [comment]
Sounds good... I just read back through it and felt like it was a ton of information in one issue and that it would be hard to keep track of it all... I'm going to break it up and close this issue.
