### ISSUE TITLE
Extra Pages Label

### ISSUE THREAD

**Issue by ChristineP2** [devnacho/mountain_view#78]
Is there a way to override the Extra Pages Label?  If yes, I'll document it and add it to the readme, if no, I propose adding it as a setting, then documenting it and adding it to the readme.

**Comment by kitop** [comment]
> So, I started into doing this and then I started wondering Should these be in an i18n en.yml file somewhere instead? It seems like if we moved all that into translation, they'd be able to override the titles, and also translate them as needed. See PR #79

That's a great idea!!! Looking at the PR now 😄 

> I'm going to try and dedicate a few more hours this weekend, but I may have to roll into next week to do more. Thanks for all your comments and insight! I'm really enjoying this 😸

Thank you for contributing!! And no worries about time, there are absolutely no hurries :)

**Comment by kitop** [comment]
Closed in #79

**Comment by kitop** [comment]
Closed in #79
